### PR TITLE
Update generate.rb

### PR DESCRIPTION
**Pull request by D3vil0p3r**

### CODE REVIEW

**Comment by noraj** [comment]
I have been working on some modifications on branch [pr-35](https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/compare/master...pr-35) (see https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/commit/2d9e6e5b9cc9fd751b1589f9f1cd230c693ae28f) based on your work (I'm not done yet).

**Comment by D3vil0p3r** [comment]
> I have been working on some modifications on branch [pr-35](https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/compare/master...pr-35) (see [2d9e6e5](https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/commit/2d9e6e5b9cc9fd751b1589f9f1cd230c693ae28f)) based on your work (I'm not done yet).

I gave a look to the code. Currently it seems good. About the ASCII art banner, don't you like to keep?

**Comment by noraj** [comment]
> I gave a look to the code. Currently it seems good.

Copying template without args and rendering with args feeled unnatural  so I introduced sub-commands (init and generate). For sub-commands I needed optparse instead. I also made the args optional so if they are not set the value is asked by the prompt. I fixed some linting. I'll try to rubyfy some system commands to and finish the linting. Then I'll test the PKGBUILD.
Yes I removed the ASCII banner, it was too huge. We can maybe re-introduced something with a smaller height.

**Comment by noraj** [comment]
In dcc4f94eae05fe6f13d4fa6bc24e020158d094fd, I have also removed to the _per exam color_ to just keep one, this is less disturbing and gives a better experience. I have added a bunch of options, finished linting (pass 100% of default rubocop), replaced the call to system `sed` to pure ruby, add a dynamic list of syntax highlight, adjusted the coloration to the critical info and a bunch of other small enhancements. I'll push that in #36.

**Comment by noraj** [comment]
I squashed both our work in https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/commit/4eea11caaad0720219758afbc24375a798786de2. @D3vil0p3r I'll tweet about the new report generator if you want to share your twitter handle with me.

**Comment by noraj** [comment]
@D3vil0p3r Thanks, 🙏🏻 ❤️ that's a great collaboration we made.

**Comment by D3vil0p3r** [comment]
> I squashed both our work in https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/commit/4eea11caaad0720219758afbc24375a798786de2. @D3vil0p3r I'll tweet about the new report generator if you want to share your twitter handle with me.

Hey. Sadly I don't have twitter account anymore. I use only Linkedin as social network ^^'

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r Thanks, 🙏🏻 ❤️ that's a great collaboration we made.

I agree. I saw several your projects. Very good mind.

**Pull request closed without merging**
