### PR TITLE
Added OSWA certification

### PR DESCRIPTION
**Pull request by reversebrain**

### CODE REVIEW

**Comment by noraj** [comment]
- Exam acronym: OSWA
- Exam name: Offensive Security Web Assessor
- Lab acronym: WAKL
- Lab name: Web Attacks with Kali Linux
- Course designation: WEB-200
- Page: https://www.offensive-security.com/web200-oswa/
- Template: https://help.offensive-security.com/hc/en-us/articles/4410105650964-OSWA-Exam-Guide#suggested-documentation-templates

**Comment by noraj** [comment]
Hi @reversebrain 
Awesome, thanks for the contribution.
Could you add the needed changes to the README too?

**Comment by reversebrain** [comment]
> Hi @reversebrain Awesome, thanks for the contribution. Could you add the needed changes to the README too?

Hi @noraj, I committed the changes you requested

**Comment by noraj** [comment]
@reversebrain Thanks!

**Pull request merged**
